#!/usr/bin/env python3
"""
Regenerate logos.js: the 32 team crests, 48px, inlined as base64.

WHY THIS IS A SCRIPT AND NOT A FILE IN THE REPO
-----------------------------------------------
logos.js is 123KB of base64-encoded PNG. It does not compress -- gzipping
already-compressed image data and re-encoding it to base64 comes out slightly
LARGER than the original -- and it is the one file in this project too big to
move through the API the rest of the code was pushed with.

Generating it is better than storing it anyway. The crests are derived data:
they come from a public index of team logos, and a script that says where they
came from is more honest than a blob nobody can audit.

WHERE IT RUNS
-------------
The GitHub Action. Both logo hosts are blocked from the model's own sandbox by
its egress allowlist, so this cannot be tested there -- the Action is where it
is proven, and the checks at the bottom are written to fail loudly rather than
write a half-finished file.

    python make_logos.py            # writes logos.js
    python make_logos.py --check    # verify an existing logos.js, write nothing
"""
import base64, io, json, sys, urllib.request

INDEX = ("https://raw.githubusercontent.com/nflverse/nflfastR-data/master/"
         "teams_colors_logos.csv")
SIZE = 48
# The board's own codes. The index also carries LAR, OAK, SD and STL, which are
# former names for teams already in this list, so they are left out rather than
# producing two crests for one team.
TEAMS = ["ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL", "DEN",
         "DET", "GB", "HOU", "IND", "JAX", "KC", "LA", "LAC", "LV", "MIA",
         "MIN", "NE", "NO", "NYG", "NYJ", "PHI", "PIT", "SEA", "SF", "TB",
         "TEN", "WAS"]

HEADER = ("// 48px team logos, generated by make_logos.py from the nflverse team\n"
          "// index and inlined so the board never depends on a CDN and renders\n"
          "// identically offline. Keyed by the same team codes as window.TEAM.\n")

UA = {"User-Agent": "TransferSportal/1.0 (NFL model; github.com/TransferSportal)"}


def fetch(url, timeout=60):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers=UA), timeout=timeout).read()


def index():
    """team code -> the logo URLs to try, best first."""
    import csv as _csv
    text = fetch(INDEX).decode("utf-8", "replace")
    rows = list(_csv.DictReader(io.StringIO(text)))
    out = {}
    for r in rows:
        code = (r.get("team_abbr") or "").strip()
        if code not in TEAMS:
            continue
        urls = [r.get(k, "").strip() for k in
                ("team_logo_espn", "team_logo_squared", "team_logo_wikipedia")]
        out[code] = [u for u in urls if u.startswith("http")]
    return out


def square(raw, size=SIZE):
    """Fit the art inside a transparent square, so crests of different aspect
    ratios all land on the same 48x48 canvas and line up in a row."""
    from PIL import Image
    im = Image.open(io.BytesIO(raw)).convert("RGBA")
    im.thumbnail((size, size), Image.LANCZOS)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.paste(im, ((size - im.width) // 2, (size - im.height) // 2), im)
    buf = io.BytesIO()
    canvas.save(buf, "PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def check(path="logos.js"):
    """Prove an existing logos.js is 32 distinct, decodable 48x48 crests."""
    from PIL import Image
    src = open(path, encoding="utf-8").read()
    # split on the FIRST '=' only: base64 padding contains '=' too
    crests = json.loads(src.split("=", 1)[1].strip().rstrip(";"))
    missing = [t for t in TEAMS if t not in crests]
    extra = [t for t in crests if t not in TEAMS]
    if missing or extra:
        raise SystemExit(f"team mismatch -- missing {missing}, unexpected {extra}")
    seen = {}
    for code, b64 in crests.items():
        raw = base64.b64decode(b64)
        im = Image.open(io.BytesIO(raw))
        if im.size != (SIZE, SIZE):
            raise SystemExit(f"{code} is {im.size}, expected ({SIZE}, {SIZE})")
        if raw in seen:
            raise SystemExit(f"{code} and {seen[raw]} are the same image")
        seen[raw] = code
    print(f"logos.js: {len(crests)} teams, all {SIZE}x{SIZE}, all distinct, "
          f"{len(src):,} bytes")
    return crests


def build(path="logos.js"):
    urls = index()
    missing = [t for t in TEAMS if not urls.get(t)]
    if missing:
        raise SystemExit(f"no logo URL in the index for: {missing}")

    crests, failed = {}, {}
    for code in TEAMS:
        for u in urls[code]:
            try:
                crests[code] = square(fetch(u))
                break
            except Exception as e:
                failed.setdefault(code, []).append(f"{u.split('/')[2]}: {e}")
        else:
            continue
    still = [t for t in TEAMS if t not in crests]
    if still:
        for t in still:
            print(f"  {t}: " + " | ".join(failed.get(t, ["no source reachable"])))
        raise SystemExit(f"could not fetch {len(still)} of {len(TEAMS)} crests; "
                         f"logos.js NOT written, the old one is untouched")

    body = json.dumps({t: crests[t] for t in TEAMS}, separators=(",", ":"))
    open(path, "w", encoding="utf-8").write(f"{HEADER}window.CREST = {body};\n")
    check(path)


if __name__ == "__main__":
    if "--check" in sys.argv:
        check()
    else:
        build()
